// Mocks generated by Mockito 5.4.5 from annotations
// in wingmate/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:sqflite_common_ffi/sqflite_ffi.dart' as _i2;
import 'package:wingmate/domain/entities/voice.dart' as _i8;
import 'package:wingmate/infrastructure/data/app_database.dart' as _i6;
import 'package:wingmate/infrastructure/data/voice_dao.dart' as _i7;
import 'package:wingmate/infrastructure/services/voice_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i3.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
      ) as String);

  @override
  String get subscriptionKey => (super.noSuchMethod(
        Invocation.getter(#subscriptionKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#subscriptionKey),
        ),
      ) as String);

  @override
  _i5.Future<List<Map<String, dynamic>>> fetchVoicesFromApi() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVoicesFromApi,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i6.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);
}

/// A class which mocks [VoiceDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceDao extends _i1.Mock implements _i7.VoiceDao {
  MockVoiceDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i8.Voice>> getVoices() => (super.noSuchMethod(
        Invocation.method(
          #getVoices,
          [],
        ),
        returnValue: _i5.Future<List<_i8.Voice>>.value(<_i8.Voice>[]),
      ) as _i5.Future<List<_i8.Voice>>);

  @override
  _i5.Future<_i8.Voice?> getVoiceById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getVoiceById,
          [id],
        ),
        returnValue: _i5.Future<_i8.Voice?>.value(),
      ) as _i5.Future<_i8.Voice?>);

  @override
  _i5.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteVoice(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVoice,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveVoice(_i8.Voice? voice) => (super.noSuchMethod(
        Invocation.method(
          #saveVoice,
          [voice],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i8.Voice?> getSelectedVoice() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedVoice,
          [],
        ),
        returnValue: _i5.Future<_i8.Voice?>.value(),
      ) as _i5.Future<_i8.Voice?>);

  @override
  _i5.Future<void> saveSelectedVoice(_i8.Voice? voice) => (super.noSuchMethod(
        Invocation.method(
          #saveSelectedVoice,
          [voice],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
