name: wingmate
description: "TTS with actual great synthesis."
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.3.0
  hive: ^2.2.3
  http: ^1.2.2
  path_provider: ^2.1.5
  fluttertoast: ^8.2.8
  sqflite: ^2.4.1
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  sqflite_common_ffi: ^2.3.4+4
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_analytics: ^11.4.0
  share_plus: ^10.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

