name: wingmate
description: "TTS with actual great synthesis."
publish_to: 'none'
version: 0.2.22+16

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.3.0
  hive: ^2.2.3
  http: ^1.2.2
  path_provider: ^2.1.5
  fluttertoast: ^8.2.8
  sqflite: ^2.4.1
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  sqflite_common_ffi: ^2.3.4+4
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_analytics: ^11.4.0
  share_plus: ^10.1.3
  in_app_purchase: ^3.2.0
  photo_view: ^0.15.0
  whisper_library_dart: ^0.0.9
  whisper_library_flutter: ^0.0.9
  ggml_library_flutter: ^0.0.10
  general_lib: ^0.0.66
  permission_handler: ^11.4.0
  flutter_sound_platform_interface: ^9.25.1
  flutter_sound: ^9.25.1
  win32: ^5.10.1
  record: ^5.2.1
  record_platform_interface: ^1.2.0
  whisper_flutter_new: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

