name: wingmate
description: "TTS with actual great synthesis."
publish_to: 'none'
version: 0.2.23+24

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.7.0
  hive: ^2.2.3
  http: ^1.3.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  audioplayers: ^6.4.0
  wav: ^1.4.0
  sqflite_common_ffi: ^2.3.4+4
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_analytics: ^11.4.0
  share_plus: ^10.1.3
  in_app_purchase: ^3.2.0
  photo_view: ^0.15.0
  permission_handler: ^11.4.0
  image_picker: ^1.1.2 # For picking images from gallery
  uuid: ^4.4.0 # For generating unique filenames
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.0
  flutter_gen: ^5.10.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.7
  

  

dev_dependencies:
  reorderable_grid_view: ^2.2.0 # For drag-and-drop reordering in GridView
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.1
  mockito: ^5.0.0 # Or latest version

flutter:
  uses-material-design: true
  generate: true
