// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhK_r-siAnrLwVk7ozBLks3ra2_Pcyx8',
    appId: '1:266436383894:web:2bab46bdffecdc9fd0deb7',
    messagingSenderId: '266436383894',
    projectId: 'wingmate-2a420',
    authDomain: 'wingmate-2a420.firebaseapp.com',
    storageBucket: 'wingmate-2a420.firebasestorage.app',
    measurementId: 'G-4JHC26NV5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Dhs95v2TjWv3OvFQ_jOtDHtB-svSO1U',
    appId: '1:266436383894:android:1539493bcbc00f5dd0deb7',
    messagingSenderId: '266436383894',
    projectId: 'wingmate-2a420',
    storageBucket: 'wingmate-2a420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWYxeDYF_LVkmXozSo5lUKoZhMxoQHmE',
    appId: '1:266436383894:ios:09f0a6daf770d045d0deb7',
    messagingSenderId: '266436383894',
    projectId: 'wingmate-2a420',
    storageBucket: 'wingmate-2a420.firebasestorage.app',
    iosBundleId: 'com.example.wingmancrossplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwWYxeDYF_LVkmXozSo5lUKoZhMxoQHmE',
    appId: '1:266436383894:ios:09f0a6daf770d045d0deb7',
    messagingSenderId: '266436383894',
    projectId: 'wingmate-2a420',
    storageBucket: 'wingmate-2a420.firebasestorage.app',
    iosBundleId: 'com.example.wingmancrossplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhK_r-siAnrLwVk7ozBLks3ra2_Pcyx8',
    appId: '1:266436383894:web:83387835e864508ed0deb7',
    messagingSenderId: '266436383894',
    projectId: 'wingmate-2a420',
    authDomain: 'wingmate-2a420.firebaseapp.com',
    storageBucket: 'wingmate-2a420.firebasestorage.app',
    measurementId: 'G-W05SLC6964',
  );

}